# Generated by Django 2.2.10 on 2020-04-30 00:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='C000001', max_length=255)),
                ('category', models.CharField(choices=[('SE', 'Sedán'), ('SU', 'SUV'), ('CO', 'Coupé'), ('HA', 'Hatchback'), ('PI', 'Pick-up'), ('SW', 'Station Wagon'), ('OT', 'Otro')], default='OT', max_length=2)),
                ('model', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('number_of_doors', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('is_diesel', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='Description not provided', max_length=255)),
                ('current_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
